### ISSUE TITLE
Please share some word on how to convert a single MIB into JSON.

### ISSUE THREAD

**Issue by Kaliph** [PrimeEuler/asn2json#1]
Hello, I am struggling how to use this library, I would like to be able to convert a single smi file into json.
What is the best way to do this? Any hint would be appreciated. Thankyou

**Comment by PrimeEuler** [comment]
var asn2json    = require("asn2json");
var fs               = require('fs');
var asn            = new asn2json()
var smi            = asn.parse( fs.readFileSync("SMI.mib") )

**Comment by Kaliph** [comment]
Thanks for pointing me to that. I was more looking for somthing like that.
`{
    "RFC1155-SMI": {
        "internet": {
            "ObjectName": "internet",
            "ModuleName": "RFC1155-SMI",
            "OBJECT IDENTIFIER": "iso org(3) dod(6) 1",
            "OID": "1.3.6.1.",
            "NameSpace": "iso.org.dod.internet"
        },
        "directory": {
            "ObjectName": "directory",
            "ModuleName": "RFC1155-SMI",
            "OBJECT IDENTIFIER": "internet 1",
            "OID": "1.3.6.1.1",
            "NameSpace": "iso.org.dod.internet.directory"
        },
        "mgmt": {
            "ObjectName": "mgmt",
            "ModuleName": "RFC1155-SMI",
            "OBJECT IDENTIFIER": "internet 2",
            "OID": "1.3.6.1.2",
            "NameSpace": "iso.org.dod.internet.mgmt"
        },
        "experimental": {
            "ObjectName": "experimental",
            "ModuleName": "RFC1155-SMI",
            "OBJECT IDENTIFIER": "internet 3",
            "OID": "1.3.6.1.3",
            "NameSpace": "iso.org.dod.internet.experimental"
        },
        "private": {
            "ObjectName": "private",
            "ModuleName": "RFC1155-SMI",
            "OBJECT IDENTIFIER": "internet 4",
            "OID": "1.3.6.1.4",
            "NameSpace": "iso.org.dod.internet.private"
        },
        "enterprises": {
            "ObjectName": "enterprises",
            "ModuleName": "RFC1155-SMI",
            "OBJECT IDENTIFIER": "private 1",
            "OID": "1.3.6.1.4.1",
            "NameSpace": "iso.org.dod.internet.private.enterprises"
        },
        "OBJECT-TYPE": {
            "TYPE NOTATION": {
                "SYNTAX": "(TYPE ObjectSyntax)",
                "ACCESS": "Access",
                "STATUS": "Status"
            },
            "VALUE NOTATION": {
                "value": "(VALUE ObjectName)"
            },
            "Access": {
                "ObjectName": "Access",
                "ModuleName": "RFC1155-SMI",
                "MACRO": "\"read-only\""
            },
            "Status": {
                "ObjectName": "Status",
                "ModuleName": "RFC1155-SMI",
                "MACRO": "\"mandatory\""
            }
        },`
 Could this also be achieved with this package? I would like to get the OIDs for all values that are in a MIB.smi File which I want to output in JSON format. Thankyou

**Comment by PrimeEuler** [comment]
merged updates
